# Generated by Django 2.2.5 on 2019-10-25 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participantcompletedtask',
            options={'verbose_name': 'Completed task', 'verbose_name_plural': 'Completed tasks'},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='min_participant_req',
            new_name='max_participant',
        ),
    ]
