# Generated by Django 2.2.4 on 2019-11-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0007_task_approved_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='link_to',
            field=models.URLField(),
        ),
    ]
