# Generated by Django 3.0.2 on 2020-02-26 15:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0008_auto_20191121_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='link_to',
            field=models.URLField(validators=[django.core.validators.RegexValidator('^https:\\/\\/docs.google.com\\/forms\\/.*$', code='invalid_google_form_link', message='Enter a valid link to a google form')]),
        ),
        migrations.AlterField(
            model_name='task',
            name='max_num_participants',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(1, 'You cannot have no participants!')]),
        ),
    ]
