language: python

python:
  - "3.6"

# setup environment
env:
  - DJANGO_VERSION=3.0.2

# install dependencies
install:
  - pip install -r requirements.txt
  - pip install codecov

# run test scripts
script:
  - python3 manage.py migrate
  - coverage run manage.py test

after_success:
  - codecov
