#!/bin/bash

# Create and activate the virtual environment
python3 -m venv .venv
. .venv/bin/activate || exit 1

# Install dependencies
pip install -r requirements.txt

# Do migrations
python3 manage.py migrate

# Collect static files
python3 manage.py collectstatic --no-input

# Reload gunicorn
sudo systemctl reload-or-restart gunicorn
