# Generated by Django 2.1.7 on 2019-11-06 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0003_transaction'),
        ('participant', '0003_auto_20191031_1730'),
    ]

    operations = [
    ]
