# Generated by Django 2.1.7 on 2019-11-13 01:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0005_auto_20191112_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_posted',
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('PE', 'Pending'), ('AC', 'Active'), ('CO', 'Completed')], default='PE', max_length=2),
        ),
        migrations.AlterField(
            model_name='task',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='part', to=settings.AUTH_USER_MODEL),
        ),
    ]
