# Generated by Django 3.1.4 on 2020-12-02 01:01

import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0009_task_paid_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='multipass_username',
        ),
        migrations.AddField(
            model_name='task',
            name='major_qualifications',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Applied Mathematics and Statistics', 'Applied Mathematics and Statistics'), ('Biochemistry', 'Biochemistry'), ('Chemical Engineering', 'Chemical Engineering'), ('Chemistry', 'Chemistry'), ('Civil Engineering', 'Civil Engineering'), ('Computer Science', 'Computer Science'), ('Economics', 'Economics'), ('Electrical Engineering', 'Electrical Engineering'), ('Engineering', 'Engineering'), ('Engineering Physics', 'Engineering Physics'), ('Environmental Engineering', 'Environmental Engineering'), ('Geological Engineering', 'Geological Engineering'), ('Geophysical Engineering', 'Geophysical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Metallurgical and Materials Engineering', 'Metallurgical and Materials Engineering'), ('Mining Engineering', 'Mining Engineering'), ('Petroleum Engineering', 'Petroleum Engineering'), ('Not a Mines Student', 'Not a Mines Student')], default='Applied Mathematics and Statistics,Biochemistry,Chemical Engineering,Chemistry,Civil Engineering,Computer Science,Economics,Electrical Engineering,Engineering,Engineering Physics,Environmental Engineering,Geological Engineering,Geophysical Engineering,Mechanical Engineering,Metallurgical and Materials Engineering,Mining Engineering,Petroleum Engineering,Not a Mines Student', max_length=375),
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(default=18, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='user',
            name='anon_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='demographics_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='ethnicity',
            field=models.CharField(choices=[('White', 'White'), ('Hispanic or Latino', 'Hispanic or Latino'), ('Black or African American', 'Black or African American'), ('Native American or American Indian', 'Native American or American Indian'), ('Asian/Pacific Islander', 'Asian/Pacific Islander'), ('Other', 'Other')], default='Other', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='major',
            field=models.CharField(choices=[('Applied Mathematics and Statistics', 'Applied Mathematics and Statistics'), ('Biochemistry', 'Biochemistry'), ('Chemical Engineering', 'Chemical Engineering'), ('Chemistry', 'Chemistry'), ('Civil Engineering', 'Civil Engineering'), ('Computer Science', 'Computer Science'), ('Economics', 'Economics'), ('Electrical Engineering', 'Electrical Engineering'), ('Engineering', 'Engineering'), ('Engineering Physics', 'Engineering Physics'), ('Environmental Engineering', 'Environmental Engineering'), ('Geological Engineering', 'Geological Engineering'), ('Geophysical Engineering', 'Geophysical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Metallurgical and Materials Engineering', 'Metallurgical and Materials Engineering'), ('Mining Engineering', 'Mining Engineering'), ('Petroleum Engineering', 'Petroleum Engineering'), ('Not a Mines Student', 'Not a Mines Student')], default='Not a Mines Student', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Female', max_length=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
