# Generated by Django 2.2.4 on 2019-09-30 19:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_ID', models.AutoField(primary_key=True, serialize=False)),
                ('multipass_username', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('CWID', models.IntegerField(unique=True)),
                ('requester_ID', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('participant_ID', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
    ]
