# Generated by Django 2.2.4 on 2019-10-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_ID', models.AutoField(primary_key=True, serialize=False)),
                ('link_to', models.CharField(max_length=50)),
                ('reward_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('title', models.CharField(max_length=100)),
                ('payment_index', models.IntegerField()),
                ('description', models.CharField(max_length=1024)),
                ('posted_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_ID', models.AutoField(primary_key=True, serialize=False)),
                ('multipass_username', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('CWID', models.IntegerField(unique=True)),
                ('authorized_requester', models.BooleanField(default=False)),
                ('reward_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
