# Generated by Django 2.2.4 on 2019-09-30 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant_homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='participant_ID',
            field=models.UUIDField(default=59614922722546354829360225071689738086, editable=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='requester_ID',
            field=models.UUIDField(default=211139090687318387765449946695244323477, editable=False),
        ),
    ]
