# Generated by Django 2.2.4 on 2019-10-01 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participant_homepage', '0002_activetaskid_participantcompletedtasks_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActiveTaskID',
            new_name='RequesterActiveTaskID',
        ),
        migrations.RenameModel(
            old_name='Tag',
            new_name='Tags',
        ),
        migrations.CreateModel(
            name='RequesterPastTaskId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_ID', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participant_homepage.Users')),
            ],
        ),
    ]
