# Generated by Django 2.2.4 on 2019-10-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant_homepage', '0003_auto_20191001_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='min_participant_req',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
