name: Django CI

on:
  push:
    branches: [ spike/* ]
  pull_request:
    branches: [ spike/* ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install codecov
    - name: Run Tests
      run: |
        python manage.py makemigrations
        python manage.py migrate
        python manage.py collectstatic
        coverage run manage.py test
    - name: Deploy to Heroku
      uses: AkhileshNS/heroku-deploy@v2.0.2
      with:
          heroku_api_key: ${{secrets.HEROKU_DEV_KEY}}
          heroku_app_name: "mines-crowdsourcing-dev-leo"
          heroku_email: "leo.chely@live.fr"
